### ISSUE TITLE
Errores en el código ;)

### ISSUE THREAD

**Issue by joacozimer** [44-2-Kupa-Martin/mysql-db-colegio#1]
Linea 45:  "orientacion ('Autocad', 'Aleman') NOT NULL,"  --->  orientacion ENUM('Autocad', 'Aleman') NOT NULL,
Linea 95: "CONSTRAINT UC_HorarioCursoOptativo_naturalKey UNIQUE (FK_CursoOptativo, dia, hora),"  --->  CONSTRAINT UC_HorarioCursoOptativo_naturalKey UNIQUE (FK_CursoOptativo, dia, horaEntrada),

**Comment by tatoguima2004** [comment]
sos un mentiroso anda bien
